### ISSUE TITLE
Option to not upload for CI testing

### ISSUE THREAD

**Issue by aidanheerdegen** [uibcdf/action-build-and-upload-conda-packages#2]
There is no option to just do the build and not upload. This would be useful for a CI pipeline, to check the correctness of the `conda` configuration before trying to deploy.

In this way the configuration could be fixed at the PR stage, rather than failing at deployment, say after a pull request has been merged and a new tag pushed.

**Comment by dprada** [comment]
Hi @aidanheerdegen! Thanks for the suggestion. You are right.

Would you dare to implement the changes in a PR? If that's not the case, give me 24-48 hours to check it myself.

Thanks again.

**Comment by aidanheerdegen** [comment]
Thanks for the positive feedback. 

It's the weekend here in Australia, so won't get to this immediately. If you do start something let me know, otherwise we might be able to take a look early next week
