### ISSUE TITLE
Simplify package search

### ISSUE THREAD

**Issue by atteggiani** [uibcdf/action-build-and-upload-conda-packages#6]
Hello,
Thank you for this very useful action! 

I have a suggestion to simplify the portions of code where the search for the built package is performed: 

https://github.com/uibcdf/action-build-and-upload-conda-packages/blob/a8c0da761999a89e4c2ab498739aef503f2b57e5/action.yml#L132-L140

could be simplified to:
```bash
HOST_PACKAGE=$(find $out_dir -type f -name *.tar.bz2)
```

https://github.com/uibcdf/action-build-and-upload-conda-packages/blob/a8c0da761999a89e4c2ab498739aef503f2b57e5/action.yml#L241-L250

could be simplified to:
```bash
filenames=$(find ${{ steps.packages-compilation.outputs.out_dir }} -type f -name *.tar.bz2)
for filename in $filenames; do
    echo "anaconda upload --user ${{ inputs.user }} $force --label $label $filename"
    anaconda upload --user ${{ inputs.user }} $force --label $label $filename
done
```

I am happy to open a PR if you think the suggestions make sense.

Cheers
Davide

**Comment by dprada** [comment]
Hi Davide!
I would be really grateful if you want to help with a PR. 
Otherwise, I will happily review this issue in three days to implement your suggestion.
Thanks a lot!

**Comment by dprada** [comment]
Hi Davide!
I would be really grateful if you want to help with a PR.
Otherwise, I will happily review this issue in three days to implement your suggestion.
Thanks a lot!

**Comment by atteggiani** [comment]
I will create a PR later today.

**Comment by dprada** [comment]
Thanks!

**Comment by atteggiani** [comment]
Hi @dprada, just flagging that the related [PR](#8) was opened, forgot to do it earlier.
