### ISSUE TITLE
Preserve built package path as an output

### ISSUE THREAD

**Issue by atteggiani** [uibcdf/action-build-and-upload-conda-packages#7]
Hello, 

In the company where I work we have been using this action a lot, and we find it very useful!

However, recently I found myself needing the path of the built package (for example, to create a release with the built file(s)).
Retrieving the built package path(s) is currently not possible (at least without implementing a convoluted process that involves looking directly inside the `action.yml` to find how the `out_dir` variable is defined, etc.). 

I think it would be helpful to add the path(s) of the built package as an output of the action. 
Something like:
```yaml
outputs:
    ${{steps.packages-uploading.outputs.filenames}}
```
And adding the built packages paths as `GITHUB_OUTPUT` within the `Packages uploading` step, before (or after) uploading them to anaconda.

This would not change the behaviour of the current action, but would add a useful resource that can be properly documented in the README. 

I am happy to create a PR if you think this suggestion makes sense. 

Cheers
Davide

**Comment by dprada** [comment]
Hi Davide!
I would be really grateful if you want to help with a PR.
Otherwise, I will happily review this issue in three days to implement your suggestion.
Thanks a lot!

**Comment by atteggiani** [comment]
I will create a PR later today.

**Comment by dprada** [comment]
Thanks for your contribution!

**Comment by atteggiani** [comment]
Hi @dprada, just flagging that the related [PR](#9) was opened, forgot to do it earlier.
